version: '3'

services:
  nonotion-service:
    build: .
    container_name: nonotion-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 60s
  mongo-db:
    image: 'mongo:latest'
    restart: always
    container_name: mongo-db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: db